### ISSUE TITLE
Error because of NA

### ISSUE THREAD

**Issue by mancag** [sdcTools/cellKey#11]
Dear all,

I am testing the cellKey package version 0.18.11.
I generated my microdata, set up a table and tried to perturb it.
But I was not successful, because I get an error when I run the line
table1$perturb(v = c("data201801"))
The error is:
Error in if (abs_xj < zs) { : missing value where TRUE/FALSE needed

In the console, I get:
> table1$perturb(v = c("data201801"))
j: 1 | ck: 0.578000000000021
xj: 2425.36 | x_delta: 670.62411134 | a: 216.69950057 | v: 0.5
x_hat: 335.312055670429
updating original value: old: 145323.91 | new: 145659.22205567
j: 2 | ck: 0.780000000000215
xj: 2360.2 | x_delta: 330.63591421 | a: 440.54265068 | v: 1
x_hat: 330.63591420704
updating original value: old: 145659.22205567 | new: 145989.857969877
j: 3 | ck: 0.800000000002157
xj: 2266.28 | x_delta: 129.38364013 | a: 1128.34866774 | v: 1
x_hat: 129.383640131454
updating original value: old: 145989.857969877 | new: 146119.241610009
j: 1 | ck: 0.645859999999998
xj: 2240.27 | x_delta: 642.75233248 | a: 30.16858753 | v: 0.5
x_hat: 321.37616624032
updating original value: old: 19390.93 | new: 19712.3061662403
j: 2 | ck: 0.458599999999986
xj: 2210.32 | x_delta: 318.92455918 | a: 61.80868045 | v: 0
x_hat: 0
updating original value: old: 19712.3061662403 | new: 19712.3061662403
j: 3 | ck: 0.585999999999864
xj: 2194.02 | x_delta: 127.02638778 | a: 155.18276565 | v: 0.5
x_hat: 63.5131938919976
updating original value: old: 19712.3061662403 | new: 19775.8193601323
j: 1 | ck: 0.198620000000032
xj: 2425.36 | x_delta: 670.62411134 | a: 117.75359499 | v: -1
x_hat: -670.624111340859
updating original value: old: 78968.4 | new: 78297.7758886591
j: 2 | ck: 0.986200000000321
xj: 2360.2 | x_delta: 330.63591421 | a: 236.80965232 | v: 3
x_hat: 991.907742621119
updating original value: old: 78297.7758886591 | new: 79289.6836312802
j: 3 | ck: 0.862000000003219
xj: 2154.16 | x_delta: 125.66797549 | a: 630.94581832 | v: 1.5
x_hat: 188.501963232935
updating original value: old: 79289.6836312802 | new: 79478.1855945132
j: 1 | ck: 0.770638
xj: 2177.65 | x_delta: 632.36805511 | a: 26.24076258 | v: 1
x_hat: 632.368055107586
updating original value: old: 16593.82 | new: 17226.1880551076
j: 2 | ck: 0.706387
xj: 2122.29 | x_delta: 311.37775407 | a: 55.32247513 | v: 1
x_hat: 311.377754065495
updating original value: old: 17226.1880551076 | new: 17537.5658091731
j: 3 | ck: 0.063877
xj: 1880.89 | x_delta: 564.267 | a: 31.08026131 | v: -2
x_hat: -1128.534
updating original value: old: 17537.5658091731 | new: 16409.0318091731
j: 1 | ck: 0.457950000000015
xj: 2266.28 | x_delta: 646.91820066 | a: 29.42940851 | v: 0
x_hat: 0
updating original value: old: 19038.42 | new: 19038.42
j: 2 | ck: 0.579500000000154
xj: 2213.59 | x_delta: 319.19503243 | a: 59.64510116 | v: 0.5
x_hat: 159.597516217141
updating original value: old: 19038.42 | new: 19198.0175162171
j: 3 | ck: 0.795000000001545
xj: 2194.55 | x_delta: 127.04416685 | a: 151.11293963 | v: 1
x_hat: 127.044166851882
updating original value: old: 19198.0175162171 | new: 19325.061683069
j: 1 | ck: 0.504946
xj: 1977.81 | x_delta: 593.343 | a: 19.09913827 | v: 0
x_hat: 0
updating original value: old: 11332.34 | new: 11332.34
j: 2 | ck: 0.049465
xj: 1708.81 | x_delta: 512.643 | a: 22.10571489 | v: -2.5
x_hat: -1281.6075
updating original value: old: 11332.34 | new: 10050.7325
j: 3 | ck: 0.49465
xj: 1450.57 | x_delta: 435.171 | a: 23.09605305 | v: 0
x_hat: 0
updating original value: old: 10050.7325 | new: 10050.7325
j: 1 | ck: 0.975329999999999
xj: 2425.36 | x_delta: 670.62411134 | a: 36.06030501 | v: 3
x_hat: 2011.87233402258
updating original value: old: 24182.91 | new: 26194.7823340226
j: 2 | ck: 0.753299999999999
xj: 1856.37 | x_delta: 556.911 | a: 47.03585013 | v: 1
x_hat: 556.911
updating original value: old: 26194.7823340226 | new: 26751.6933340226
j: 3 | ck: 0.532999999999997
xj: 1842.58 | x_delta: 552.774 | a: 48.39535386 | v: 0
x_hat: 0
updating original value: old: 26751.6933340226 | new: 26751.6933340226
j: 1 | ck: 0.7735
xj: 1314.92 | x_delta: 394.476 | a: 5.85870877 | v: 1
x_hat: 1183.428
updating original value: old: 2311.12 | new: 3494.548
j: 2 | ck: 0.73507
xj: 996.2 | x_delta: 298.86 | a: 11.69292645 | v: 1
x_hat: 896.58
updating original value: old: 3494.548 | new: 4391.128
j: 3 | ck: 0.35077
Error in if (abs_xj < zs) { : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used
2: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used
3: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used
4: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used
5: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used
6: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used
7: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used
8: In if (ck == 0) { :
  the condition has length > 1 and only the first element will be used

What should I do?
I enclose my code (to run it, folder path0 has to be created with subsolders path1, path2, path3).
[use_of_ckm_v1.txt](https://github.com/sdcTools/cellKey/files/5074675/use_of_ckm_v1.txt)

Best regards,
Manca

**Comment by bernhard-da** [comment]
hi @mancag thx for the report. in order to track this issue I would need access to the microdata you used; is it possible for you to share those with me?

**Comment by mancag** [comment]
Dear Mr. Meindl,

I send you the microdata.
The microdata can be also generated using my code.

Best,
Manca Golmajer

V V tor., 18. avg. 2020 ob 14:14 je oseba bernhard-da <
notifications@github.com> napisala:

**Comment by bernhard-da** [comment]
hi @mancag ; i was able to reproduce and (hopefully) fix the error in version `0.18.12` i just pushed. could you please check if everything works as expected?

**Comment by bernhard-da** [comment]
should be resolved; please re-open if the issue still persists in newer versions
