### ISSUE TITLE
Testing the 'destatis' functionality

### ISSUE THREAD

**Issue by tenderle** [sdcTools/cellKey#2]
Hi Bernhard,

I tested your implementation using _type='destatis'_ and externally generated record keys and then cross checked the results with our SAS implementation. I got the same perturbed tables. It works fine. Thx for the implementation so far.

One of you slots in class **pert_table** is called **cellKeys** and defined as integer. It works with the 'abs' implementation. However, using _type='destatis'_ results in zeroes since the 'destatis'-formatted cell keys are numeric.

Is it possible to change it such that the 'destatis'-formatted cell keys are part of the output?

Thx, 
Tobias

**Comment by bernhard-da** [comment]
thx @tenderle for spotting this, can you try again if the issue is indeed fixed?

**Comment by tenderle** [comment]
thx @bernhard-da for the quick fix. I also cross checked the cell keys and they are identical.

**Comment by bernhard-da** [comment]
@tenderle thx for reporting back.
