### ISSUE TITLE
Package installation problem

### ISSUE THREAD

**Issue by CrystalPalace** [sdcTools/cellKey#7]
Hello,
I receive an error when i run this command : 

install_github(
    repo = "sdcTools/cellKey", 
    force = TRUE
)

Error message :

Installing package into ‘XXXXXXXXX/3.4’
(as ‘lib’ is unspecified)
* installing *source* package ‘cellKey’ ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error : object ‘add_nodes’ is not exported by 'namespace:sdcTable'
ERROR: lazy loading failed for package ‘cellKey’
* removing ‘XXXXXXXXXXXXX/3.4/cellKey’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpGpvGVc/file5c84f85c6f4/cellKey_0.15.1.tar.gz’ had non-zero exit status

Can someone help me ?

**Comment by bernhard-da** [comment]
hi @ChystalPalace

i am aware of the problem and will provide a fix and updated instructions later today.

**Comment by bernhard-da** [comment]
@CrystalPalace i've updated (and simplified) the installation instructions in the readme. the following should now work:

```
if (!require("devtools")) install.packages("devtools")

# install with all dependencies
remotes::install_github(
  repo = "sdcTools/cellKey",
  ref = "master",
  dependencies = TRUE,
  build_opts = "--no-resave-data",
  force = TRUE
)
```

**Comment by CrystalPalace** [comment]
Thanks you for the quick reply !
Now i get this error : 

 checking for file ‘/XXXXXXX/remotes7261ab42db4/sdcTools-cellKey-ab77ba9/DESCRIPTION’ (629ms)
─  preparing ‘cellKey’:
  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes (352ms)
E  creating vignettes (17.2s)
   pandoc: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
   Aborted (core dumped)
   Warning: running command ''/usr/lib/XXXXXXX/bin/pandoc/pandoc' --version' had status 134
   Error: processing vignette 'introduction.Rmd' failed with diagnostics:
   subscript out of bounds
   Execution halted
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error

But i suppose the problem come from pandoc...

**Comment by bernhard-da** [comment]
hi @CrystalPalace 

yes, this issue seems to be pandoc specific and unrelated to cellKey. As you can [see here](https://travis-ci.org/sdcTools/cellKey), the builds are all passing (including package vignettes).
