### ISSUE TITLE
error: Error in if (type == "abs") { : argument is of length zero

### ISSUE THREAD

**Issue by pnicky** [sdcTools/cellKey#8]
Hello,
my code:

HC_92_HU<- read.csv2("H:/munkafile-ok/hc_92_1010_minta_egyben.csv", header=TRUE, sep=";", dec=",", fill=TRUE)
colnames(HC_92_HU)<-c("geo_m", "sex", "age_m", "yae_h", "usual_resident", "spv_cov_imputation_flag")

head(HC_92_HU)

set.seed(123)
options(scipen=999)
HC_92_HU$recordkey<-runif(dim(HC_92_HU)[1])
head(HC_92_HU)

params_new <- pt_create_pParams(D=2, V=0.9)
ptable_destatis_new <- pt_create_pTable(params = params_new, type = "destatis")

inp <- ck_create_input( dat=HC_92_HU, def_rkey="recordkey", pert_params=params_new)

Error:
Error in if (type == "abs") { : argument is of length zero

Can you please help?
Thank you!

**Comment by bernhard-da** [comment]
@pnicky could you please somehow provide the test input file (`hc_92_1010_minta_egyben.csv`) and also the output of

```
devtools::session_info()
```

thx

**Comment by pnicky** [comment]
Hello, the file looks somehow like this (2000 rows from the HC9.2):

> HC_92_HU<- read.csv2("H:/munkafile-ok/hc_92_1010_minta_egyben.csv", header=TRUE, sep=";", dec=",", fill=TRUE)
> colnames(HC_92_HU)<-c("geo_m", "sex", "age_m", "yae_h", "usual_resident", "spv_cov_imputation_flag")
> head(HC_92_HU)

  geo_m sex age_m yae_h usual_resident spv_cov_imputation_flag
1 HU313  1.  4.1.    3.              1                       0
2 HU313  2.  4.2.    3.              1                       0
3 HU313  1.  3.1.    3.              1                       0
4 HU313  1.  2.2.    3.              1                       0
5 HU313  1.  4.1.    2.              1                       0
6 HU313  2.  4.1.    2.              1                       0

> devtools::session_info()
- Session info -------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Hungarian_Hungary.1250      
 ctype    Hungarian_Hungary.1250      
 tz       Europe/Prague               
 date     2019-05-10                  

- Packages -----------------------------------------------------------------------------------------------------------------------------
 package       * version    date       lib source                           
 assertthat      0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                   
 backports       1.1.4      2019-04-10 [1] CRAN (R 3.5.3)                   
 bindr           0.1.1      2018-03-13 [1] CRAN (R 3.5.1)                   
 bindrcpp        0.2.2      2018-03-29 [1] CRAN (R 3.5.1)                   
 brew            1.0-6      2011-04-13 [1] CRAN (R 3.5.0)                   
 callr           3.2.0      2019-03-15 [1] CRAN (R 3.5.3)                   
 cellKey       * 0.15.1     2019-01-31 [1] Github (sdcTools/cellKey@7bc90a3)
 cli             1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                   
 colorspace      1.4-0      2019-01-13 [1] CRAN (R 3.5.2)                   
 crayon          1.3.4      2017-09-16 [1] CRAN (R 3.5.3)                   
 data.table    * 1.12.0     2019-01-13 [1] CRAN (R 3.5.2)                   
 data.tree       0.7.8      2018-09-24 [1] CRAN (R 3.5.1)                   
 desc            1.2.0      2018-05-01 [1] CRAN (R 3.5.3)                   
 devtools        2.0.2      2019-04-08 [1] CRAN (R 3.5.3)                   
 DiagrammeR      1.0.0      2018-03-01 [1] CRAN (R 3.5.1)                   
 digest          0.6.18     2018-10-10 [1] CRAN (R 3.5.3)                   
 downloader      0.4        2015-07-09 [1] CRAN (R 3.5.1)                   
 dplyr           0.7.8      2018-11-10 [1] CRAN (R 3.5.1)                   
 evaluate        0.12       2018-10-09 [1] CRAN (R 3.5.1)                   
 flexdashboard   0.5.1.1    2018-06-29 [1] CRAN (R 3.5.1)                   
 fs              1.2.7      2019-03-19 [1] CRAN (R 3.5.3)                   
 ggplot2         3.1.0      2018-10-25 [1] CRAN (R 3.5.1)                   
 glue            1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                   
 gridExtra       2.3        2017-09-09 [1] CRAN (R 3.5.1)                   
 gtable          0.2.0      2016-02-26 [1] CRAN (R 3.5.1)                   
 hms             0.4.2      2018-03-10 [1] CRAN (R 3.5.1)                   
 htmltools       0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                   
 htmlwidgets     1.3        2018-09-30 [1] CRAN (R 3.5.1)                   
 igraph          1.2.2      2018-07-27 [1] CRAN (R 3.5.1)                   
 influenceR      0.1.0      2015-09-03 [1] CRAN (R 3.5.1)                   
 jsonlite        1.6        2018-12-07 [1] CRAN (R 3.5.3)                   
 knitr           1.21       2018-12-10 [1] CRAN (R 3.5.1)                   
 lattice         0.20-38    2018-11-04 [1] CRAN (R 3.5.3)                   
 lazyeval        0.2.1      2017-10-29 [1] CRAN (R 3.5.1)                   
 lpSolveAPI      5.5.2.0-17 2016-01-13 [1] CRAN (R 3.5.0)                   
 magrittr        1.5        2014-11-22 [1] CRAN (R 3.5.3)                   
 memoise         1.1.0      2017-04-21 [1] CRAN (R 3.5.3)                   
 munsell         0.5.0      2018-06-12 [1] CRAN (R 3.5.1)                   
 nloptr          1.2.1      2018-10-03 [1] CRAN (R 3.5.1)                   
 pillar          1.3.1      2018-12-15 [1] CRAN (R 3.5.2)                   
 pkgbuild        1.0.3      2019-03-20 [1] CRAN (R 3.5.3)                   
 pkgconfig       2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                   
 pkgload         1.0.2      2018-10-29 [1] CRAN (R 3.5.3)                   
 plyr            1.8.4      2016-06-08 [1] CRAN (R 3.5.1)                   
 prettyunits     1.0.2      2015-07-13 [1] CRAN (R 3.5.3)                   
 primes          0.1.0      2015-06-22 [1] CRAN (R 3.5.1)                   
 processx        3.3.0      2019-03-10 [1] CRAN (R 3.5.3)                   
 ps              1.3.0      2018-12-21 [1] CRAN (R 3.5.3)                   
 ptable        * 0.2.0      2018-12-11 [1] Github (sdcTools/ptable@5651991) 
 purrr           0.3.2      2019-03-15 [1] CRAN (R 3.5.3)                   
 R6              2.4.0      2019-02-14 [1] CRAN (R 3.5.3)                   
 RColorBrewer    1.1-2      2014-12-07 [1] CRAN (R 3.5.0)                   
 Rcpp            1.0.1      2019-03-17 [1] CRAN (R 3.5.3)                   
 readr           1.3.1      2018-12-21 [1] CRAN (R 3.5.2)                   
 remotes         2.0.4      2019-04-10 [1] CRAN (R 3.5.3)                   
 rgexf           0.15.3     2015-03-24 [1] CRAN (R 3.5.1)                   
 Rglpk           0.6-3      2017-05-18 [1] CRAN (R 3.5.0)                   
 rlang           0.3.4      2019-04-07 [1] CRAN (R 3.5.3)                   
 rmarkdown       1.11       2018-12-08 [1] CRAN (R 3.5.1)                   
 Rook            1.1-1      2014-10-20 [1] CRAN (R 3.5.0)                   
 rprojroot       1.3-2      2018-01-03 [1] CRAN (R 3.5.3)                   
 rstudioapi      0.10       2019-03-19 [1] CRAN (R 3.5.3)                   
 scales          1.0.0      2018-08-09 [1] CRAN (R 3.5.1)                   
 sdcTable        0.26       2019-01-18 [1] CRAN (R 3.5.2)                   
 sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 3.5.3)                   
 slam            0.1-44     2018-12-21 [1] CRAN (R 3.5.2)                   
 stringi         1.2.4      2018-07-20 [1] CRAN (R 3.5.1)                   
 stringr         1.3.1      2018-05-10 [1] CRAN (R 3.5.1)                   
 tibble          2.0.1      2019-01-12 [1] CRAN (R 3.5.2)                   
 tidyr           0.8.2      2018-10-28 [1] CRAN (R 3.5.1)                   
 tidyselect      0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                   
 usethis         1.5.0      2019-04-07 [1] CRAN (R 3.5.3)                   
 viridis         0.5.1      2018-03-29 [1] CRAN (R 3.5.1)                   
 viridisLite     0.3.0      2018-02-01 [1] CRAN (R 3.5.1)                   
 visNetwork      2.0.5      2018-12-05 [1] CRAN (R 3.5.1)                   
 withr           2.1.2      2018-03-15 [1] CRAN (R 3.5.3)                   
 xfun            0.4        2018-10-23 [1] CRAN (R 3.5.1)                   
 XML             3.98-1.16  2018-08-19 [1] CRAN (R 3.5.1)                   
 yaml            2.2.0      2018-07-25 [1] CRAN (R 3.5.2)                   

[1] \\jumbo/userdoc/bud07211/R/R-3.5.3/library

Thanks!

**Comment by bernhard-da** [comment]
@pnicky 

you could try to use the cell key functions (note the `ck_*` instead of the `pt_` from ptable) to create the ptables. these "wrap" the functionality anyway. so try

````
# omitted data generation 
# ...

params <- ck_create_pert_params(
  pTable = ck_create_pTable(
    D = 5, 
    V = 3, 
    type= "destatis" 
  )
)
inp <- ck_create_input(
  dat = HC_92_HU, 
  def_rkey="recordkey", 
  pert_params=params
)
```

**Comment by pnicky** [comment]
@Bernhard-da, thank you, it is working perfectly!
Also, I tried this and this was also good:

pert_params2 <- ck_create_pert_params(pTable=ck_create_pTable(D=4,V=0.4, pstay=c(0.9,0.9,0.9, 0.9),type="destatis" ))
inp <- ck_create_input( dat=HC_92_HU, def_rkey="recordkey", pert_params=pert_params2)

Another question: what is the minimum requirement of R version for these codes? I tried 3.4 under Linux and it seems it was not good. As far as I know,, R 3.6 in not available under Linux yet. I need 3.5 I suppose but I haven't find it in the docs.

**Comment by bernhard-da** [comment]
@pnicky it should not depend on the r version at all. most issues are due to different versions of the loaded packages. in case you have specific problems, please just open new issues and also post the `devtools::session_info()` output ...
