### ISSUE TITLE
error with reaching library(cellKey)

### ISSUE THREAD

**Issue by pnicky** [sdcTools/cellKey#9]
Hi,
I've worked with the cellkey package last week and it was OK. Today, I cannot use the package:

library(cellKey)
Error: package or namespace load failed for ‘cellKey’:
 object ‘add_nodes’ is not exported by 'namespace:sdcTable'
I found this error but I don't know the date:
https://www.gitmemory.com/issue/sdcTools/UserSupport/113/488066782
Thanks

> devtools::session_info()
- Session info -----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Hungarian_Hungary.1250      
 ctype    Hungarian_Hungary.1250      
 tz       Europe/Prague               
 date     2019-05-20                  

- Packages ---------------------------------------------------------------------------------------------------------------------------
 package        * version    date       lib source                          
 assertthat       0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                  
 backports        1.1.4      2019-04-10 [1] CRAN (R 3.5.3)                  
 callr            3.2.0      2019-03-15 [1] CRAN (R 3.5.3)                  
 cli              1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                  
 colorspace       1.4-1      2019-03-18 [1] CRAN (R 3.5.3)                  
 crayon           1.3.4      2017-09-16 [1] CRAN (R 3.5.3)                  
 data.table     * 1.12.2     2019-04-07 [1] CRAN (R 3.5.3)                  
 desc             1.2.0      2018-05-01 [1] CRAN (R 3.5.3)                  
 devtools         2.0.2      2019-04-08 [1] CRAN (R 3.5.3)                  
 digest           0.6.18     2018-10-10 [1] CRAN (R 3.5.3)                  
 dplyr            0.8.1      2019-05-14 [1] CRAN (R 3.5.3)                  
 evaluate         0.13       2019-02-12 [1] CRAN (R 3.5.3)                  
 flexdashboard    0.5.1.1    2018-06-29 [1] CRAN (R 3.5.1)                  
 fs               1.3.1      2019-05-06 [1] CRAN (R 3.5.3)                  
 ggplot2          3.1.1      2019-04-07 [1] CRAN (R 3.5.3)                  
 glue             1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                  
 gtable           0.3.0      2019-03-25 [1] CRAN (R 3.5.3)                  
 htmltools        0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                  
 httpuv           1.5.1      2019-04-05 [1] CRAN (R 3.5.3)                  
 jsonlite         1.6        2018-12-07 [1] CRAN (R 3.5.3)                  
 knitr            1.23       2019-05-18 [1] CRAN (R 3.5.3)                  
 later            0.8.0      2019-02-11 [1] CRAN (R 3.5.3)                  
 lattice          0.20-38    2018-11-04 [1] CRAN (R 3.5.3)                  
 lazyeval         0.2.2      2019-03-15 [1] CRAN (R 3.5.3)                  
 lpSolveAPI       5.5.2.0-17 2016-01-13 [1] CRAN (R 3.5.0)                  
 magrittr         1.5        2014-11-22 [1] CRAN (R 3.5.3)                  
 memoise          1.1.0      2017-04-21 [1] CRAN (R 3.5.3)                  
 mime             0.6        2018-10-05 [1] CRAN (R 3.5.2)                  
 munsell          0.5.0      2018-06-12 [1] CRAN (R 3.5.1)                  
 nloptr           1.2.1      2018-10-03 [1] CRAN (R 3.5.1)                  
 pillar           1.4.0      2019-05-11 [1] CRAN (R 3.5.3)                  
 pkgbuild         1.0.3      2019-03-20 [1] CRAN (R 3.5.3)                  
 pkgconfig        2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                  
 pkgload          1.0.2      2018-10-29 [1] CRAN (R 3.5.3)                  
 plyr             1.8.4      2016-06-08 [1] CRAN (R 3.5.1)                  
 prettyunits      1.0.2      2015-07-13 [1] CRAN (R 3.5.3)                  
 primes           0.1.0      2015-06-22 [1] CRAN (R 3.5.1)                  
 processx         3.3.1      2019-05-08 [1] CRAN (R 3.5.3)                  
 promises         1.0.1      2018-04-13 [1] CRAN (R 3.5.1)                  
 ps               1.3.0      2018-12-21 [1] CRAN (R 3.5.3)                  
 ptable           0.2.0      2018-12-11 [1] Github (sdcTools/ptable@5651991)
 purrr            0.3.2      2019-03-15 [1] CRAN (R 3.5.3)                  
 R6               2.4.0      2019-02-14 [1] CRAN (R 3.5.3)                  
 RColorBrewer     1.1-2      2014-12-07 [1] CRAN (R 3.5.0)                  
 Rcpp             1.0.1      2019-03-17 [1] CRAN (R 3.5.3)                  
 remotes          2.0.4      2019-04-10 [1] CRAN (R 3.5.3)                  
 Rglpk            0.6-4      2019-02-09 [1] CRAN (R 3.5.2)                  
 rlang            0.3.4      2019-04-07 [1] CRAN (R 3.5.3)                  
 rmarkdown        1.12       2019-03-14 [1] CRAN (R 3.5.3)                  
 rprojroot        1.3-2      2018-01-03 [1] CRAN (R 3.5.3)                  
 rstudioapi       0.10       2019-03-19 [1] CRAN (R 3.5.3)                  
 scales           1.0.0      2018-08-09 [1] CRAN (R 3.5.1)                  
 sdcHierarchies   0.18       2019-04-23 [1] CRAN (R 3.5.3)                  
 sdcTable         0.27       2019-02-28 [1] CRAN (R 3.5.3)                  
 sessioninfo      1.1.1      2018-11-05 [1] CRAN (R 3.5.3)                  
 shiny            1.3.2      2019-04-22 [1] CRAN (R 3.5.3)                  
 shinyjs          1.0        2018-01-08 [1] CRAN (R 3.5.3)                  
 shinythemes      1.1.2      2018-11-06 [1] CRAN (R 3.5.3)                  
 shinyTree        0.2.6      2018-10-05 [1] CRAN (R 3.5.3)                  
 slam             0.1-45     2019-02-26 [1] CRAN (R 3.5.2)                  
 stringi          1.4.3      2019-03-12 [1] CRAN (R 3.5.3)                  
 stringr          1.4.0      2019-02-10 [1] CRAN (R 3.5.3)                  
 tibble           2.1.1      2019-03-16 [1] CRAN (R 3.5.3)                  
 tidyselect       0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                  
 usethis          1.5.0      2019-04-07 [1] CRAN (R 3.5.3)                  
 withr            2.1.2      2018-03-15 [1] CRAN (R 3.5.3)                  
 xfun             0.7        2019-05-14 [1] CRAN (R 3.5.3)                  
 xtable           1.8-4      2019-04-21 [1] CRAN (R 3.5.3)                  
 yaml             2.2.0      2018-07-25 [1] CRAN (R 3.5.2)

**Comment by bernhard-da** [comment]
hi @pnicky, please just update cellKey and it should work

```
remotes::install_github(
  repo = "sdcTools/cellKey", 
  force = TRUE, 
  build_opts = "--no-resave-data"
)
```

**Comment by pnicky** [comment]
thanks!

**Comment by bernhard-da** [comment]
@pnicky no worries, hope everything is solved now!
